import type { PortfolioData } from './types';
import profileImg from './assets/profile.jpg';

export const personalLinks = {
    github: 'https://github.com/bala-rajesh',
    linkedin: 'https://www.linkedin.com/in/kunapareddy-bala-rajesh-137a21214',
    email: 'mailto:kunapareddybalarajesh@gmail.com',
    emailAddress: 'kunapareddybalarajesh@gmail.com',
    resume: 'https://drive.google.com/file/d/1nJXK7DR9FKVsuosfRhbVDYhErTLZaf1h/view?usp=sharing',
};

export const projectLinks = {
    chitrakar: {
        liveUrl: 'https://chitrakar-app.vercel.app/',
        githubUrl: 'https://github.com/bala-rajesh/ChitraKara',
    },
    alzheimerParkinson: {
        liveUrl: 'https://alzhiemerparkinson.vercel.app/',
        githubUrl: 'https://github.com/bala-rajesh/Alzheimer-and-Parkinson-Prediction',
        paperUrl: 'https://ieeexplore.ieee.org/document/11336514',
    },
    retinopathy: {
        liveUrl: 'https://retinopathy-murex.vercel.app/',
        githubUrl: 'https://github.com/bala-rajesh/Retinopathy-FE',
    },
};

export const experienceLinks = {
    infosys: {
        githubUrl: 'https://github.com/bala-rajesh/QuickServe-Localized-Service-Discovery-and-Booking-App',
    },
};

export const certificateLinks = {
    infosys: 'https://infyspringboard.onwingspan.com/public-assets/infosysheadstart/cert/lex_auth_01452057076441088015/9bd95189-aa0c-4dcc-a8da-6fc86007b284.pdf',
    geeksForGeeks: 'https://media.geeksforgeeks.org/certificates/1751870662/a5c1365ea1eceae47f8d55c5f0a71cba.pdf',
};

const images = {
    code: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1400&auto=format&fit=crop',
    research: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=1000&auto=format&fit=crop',
    retina: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1000&auto=format&fit=crop',
    art: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=1000&auto=format&fit=crop',
    office: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1000&auto=format&fit=crop',
    team: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1000&auto=format&fit=crop',
    java: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?q=80&w=1000&auto=format&fit=crop',
    react: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=1000&auto=format&fit=crop',
    python: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?q=80&w=1000&auto=format&fit=crop',
    campus: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=1000&auto=format&fit=crop',
    books: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=1000&auto=format&fit=crop',
};

export const PORTFOLIO_DATA: PortfolioData = {
    hero: {
        id: 'hero',
        title: 'The Documentary of Life',
        subtitle: 'Bala Rajesh',
        description: 'A developer documenting what I build, learn, research and discover across full-stack engineering and intelligent systems.',
        longDescription: 'Software Engineer and full-stack developer specializing in Java, Spring Boot, React, and artificial intelligence systems. This archive documents real-world products, research discoveries, and engineering milestones.',
        image: images.code,
        year: '2026',
        season: 'S01',
        episode: 'E01',
        matchPercentage: 99,
        maturityRating: 'CSE 2025',
        specs: ['4K Ultra HD', 'Full Stack & AI', 'Spatial Audio'],
        isOriginal: true,
        rank: 1,
        tags: ['Java', 'React', 'AI', 'Full Stack', 'Spring Boot'],
        category: 'experience',
        role: 'Software Engineer / Full-Stack Developer',
        liveUrl: personalLinks.github,
        githubUrl: personalLinks.github,
        problem: 'How do you turn a collection of technical work and projects into an engaging, living story that visitors can explore?',
        solution: 'A cinematic documentary experience: production projects as featured episodes, technologies as a curated archive, and career progression as the storyline.',
        built: [
            'Enterprise Java & Spring Boot backend services',
            'Modern React interfaces and full-stack web applications',
            'Machine learning research and predictive diagnostic models',
            'Scalable relational and NoSQL database integrations'
        ],
        challenge: 'Maintaining technical rigor while making the interactive presentation memorable and intuitive.',
        learned: 'Great software combines analytical problem-solving, intuitive user communication, and persistent curiosity.',
    },
    sections: [
        {
            title: 'Top 10 in Software & AI Today',
            eyebrow: 'TOP 10 IN INDIA TODAY',
            variant: 'ranked',
            items: [
                {
                    id: 'project-disease',
                    title: 'Alzheimer & Parkinson Prediction',
                    subtitle: 'Published IEEE Research & Deep Learning App',
                    description: 'An AI-powered web platform for early disease detection and risk classification using EfficientNetB0 transfer learning (Published in IEEE Xplore).',
                    longDescription: 'Published IEEE research and clinical web application presenting a robust deep learning model utilizing EfficientNetB0 transfer learning from ImageNet for early detection and differentiation of Alzheimer and Parkinson diseases, achieving 98% accuracy on 7,839 clinical images.',
                    image: images.research,
                    year: '2025',
                    season: 'S01',
                    episode: 'E01',
                    rank: 1,
                    matchPercentage: 99,
                    maturityRating: 'IEEE 2025',
                    specs: ['4K Ultra HD', 'EfficientNetB0', '98% Acc'],
                    isOriginal: true,
                    runtime: 'Published Paper',
                    tags: ['IEEE Published', 'EfficientNetB0', 'Transfer Learning', 'TensorFlow', 'Python', 'React', '98% Accuracy'],
                    tech: [
                        { name: 'EfficientNetB0' },
                        { name: 'Transfer Learning' },
                        { name: 'TensorFlow & Keras' },
                        { name: 'Python' },
                        { name: 'Flask / FastAPI' },
                        { name: 'React & Tailwind' }
                    ],
                    category: 'project',
                    role: 'Lead ML Researcher & Full-Stack Developer',
                    liveUrl: projectLinks.alzheimerParkinson.liveUrl,
                    githubUrl: projectLinks.alzheimerParkinson.githubUrl,
                    paperUrl: projectLinks.alzheimerParkinson.paperUrl,
                    abstract: "This work presents a strong deep learning model that uses transfer learning from ImageNet, based on the EfficientNetB0 architecture. To ensure stability and convergence, we trained it with the Adam optimizer, data augmentation, class weighting, and effective callbacks such as Model Checkpoint, Early Stopping, and ReduceLROnPlateau over 20 epochs. The model trained on a database of 7,839 images, which included Normal (Control) and Abnormal (Parkinson's & Alzheimer's Diseases) samples from the Kaggle dataset. It achieved 98% accuracy on the validation set, showing excellent performance. We tested it using AUC and K-fold cross-validation methods, which demonstrated strong classification abilities with a weighted average Precision, Recall, and F1 score of 98%. The model, using the Adam optimizer, aimed to reduce categorical cross-entropy loss and track accuracy during training. A Flask-based online interface was developed to allow easy image uploads and offer instant diagnostic predictions for real-time use and practical application. This effective model shows great promise as a tool for early detection and differentiation of complex neurological diseases, making it useful for clinical diagnostics.",
                    problem: 'Early neurodegenerative diagnosis pipelines often suffer from lack of transfer-learning integration, high false-positive rates, and inaccessible clinical visualization interfaces.',
                    solution: 'Engineered an EfficientNetB0 deep learning architecture with transfer learning from ImageNet, validated across 7,839 medical images with K-fold cross-validation and AUC, integrated into a real-time web diagnostic system.',
                    built: [
                        'EfficientNetB0 transfer learning architecture trained on 7,839 clinical images',
                        'Achieved 98% validation accuracy, 98% weighted Precision, Recall, and F1-score',
                        'Adam optimization with ReduceLROnPlateau, Early Stopping, and class weighting callbacks',
                        'Interactive React & Flask online interface for real-time scan uploads and instant diagnostic inference',
                        'Peer-reviewed and published in IEEE Xplore (Document ID: 11336514)'
                    ],
                    challenge: 'Ensuring training stability, addressing class imbalance across Parkinson and Alzheimer samples, and achieving real-time inference latency.',
                    learned: 'Combining state-of-the-art transfer learning with rigorous K-fold validation and intuitive web interfaces delivers clinically actionable AI systems.',
                },
                {
                    id: 'project-chitrakar',
                    title: 'ChitraKara',
                    subtitle: 'Custom Art Marketplace & Platform',
                    description: 'A full-stack MERN platform connecting independent artists with buyers for custom art commissions and real-time collaboration.',
                    longDescription: 'A comprehensive creator economy platform facilitating custom artwork requests, artist discovery, automated OTP authentication, instant messaging, and secure media workflows.',
                    image: images.art,
                    year: '2024',
                    season: 'S01',
                    episode: 'E02',
                    rank: 2,
                    matchPercentage: 98,
                    maturityRating: 'LIVE APP',
                    specs: ['Full Stack', 'Cloudinary', 'Real-Time'],
                    isOriginal: true,
                    runtime: 'Live Platform',
                    tags: ['MongoDB', 'Express', 'React', 'Node.js', 'Cloudinary'],
                    tech: [
                        { name: 'MongoDB' },
                        { name: 'Express' },
                        { name: 'React' },
                        { name: 'Node.js' },
                        { name: 'Cloudinary' }
                    ],
                    category: 'project',
                    role: 'Full-Stack MERN Developer',
                    liveUrl: projectLinks.chitrakar.liveUrl,
                    githubUrl: projectLinks.chitrakar.githubUrl,
                    problem: 'Commissioning custom art is often chaotic when spread across fragmented email threads and direct messages without milestone tracking.',
                    solution: 'Built a dedicated two-sided marketplace featuring real-time client-artist chat, OTP verified security, and structured commission workflows.',
                    built: [
                        'Secure OTP authentication flow and profile management',
                        'Real-time messaging channels for artwork specs and negotiations',
                        'Cloudinary digital asset management and portfolio galleries'
                    ],
                    challenge: 'Managing bidirectional state and media uploads across multi-role artist and buyer dashboards.',
                    learned: 'Designing seamless user flows for bilateral platforms requires thorough role permissioning and responsive state architecture.',
                },
                {
                    id: 'project-retinopathy',
                    title: 'Diabetic Retinopathy Detection System',
                    subtitle: 'The Retinal Screen / AI Computer Vision',
                    description: 'A full-stack AI system that analyzes retinal fundus images and classifies diabetic retinopathy severity across five clinical stages.',
                    longDescription: 'A full-stack computer vision application for automated diabetic retinopathy screening from retinal fundus images. The system combines a React-based clinical interface with a Python deep-learning backend to process retinal images and classify disease severity across five stages: No DR, Mild, Moderate, Severe, and Proliferative DR. The frontend handles image upload and visualization of prediction results, while the backend performs image preprocessing and CNN-based inference through a REST API. The preprocessing pipeline includes image resizing, normalization, and Contrast Limited Adaptive Histogram Equalization (CLAHE) to improve image quality before inference.',
                    image: images.retina,
                    year: '2024 - 2025',
                    season: 'S01',
                    episode: 'E03',
                    rank: 3,
                    matchPercentage: 97,
                    maturityRating: 'AI VISION',
                    specs: ['CLAHE CNN', 'Docker', '5-Stage'],
                    isOriginal: true,
                    runtime: 'Screening Demo',
                    tags: ['React', 'Python', 'TensorFlow', 'OpenCV', 'CLAHE', 'CNN', 'Tailwind CSS'],
                    tech: [
                        { name: 'React' },
                        { name: 'Axios' },
                        { name: 'Python' },
                        { name: 'TensorFlow / Keras' },
                        { name: 'OpenCV' },
                        { name: 'CLAHE Pipeline' },
                        { name: 'Flask / FastAPI' },
                        { name: 'Tailwind CSS' },
                        { name: 'Docker' }
                    ],
                    category: 'project',
                    role: 'Frontend Engineering, API Integration & ML Pipeline',
                    liveUrl: projectLinks.retinopathy.liveUrl,
                    githubUrl: projectLinks.retinopathy.githubUrl,
                    problem: 'Diabetic retinopathy screening requires specialized retinal fundus image analysis, where manual evaluation can be slow, resource-constrained, and prone to diagnostic bottlenecking in high-volume clinics.',
                    solution: 'Built a full-stack screening pipeline connecting a responsive React clinical interface to a Python inference REST API with OpenCV CLAHE enhancement and CNN severity classification.',
                    built: [
                        'Frontend: Responsive React interface for retinal fundus image upload and 5-stage diagnostic severity visualization using Axios',
                        'Backend & REST API: Python REST API with a /predict endpoint returning structured severity classes, confidence scores, and status',
                        'Computer Vision Pipeline: Image preprocessing with resizing, normalization, and Contrast Limited Adaptive Histogram Equalization (CLAHE)',
                        '5-Stage Classification: Neural model mapping predictions to No DR (0), Mild (1), Moderate (2), Severe (3), and Proliferative DR (4)',
                        'Deployment Architecture: Docker containerization and Vercel cloud deployment for reliable web availability'
                    ],
                    challenge: 'Enhancing low-contrast fundus scans using CLAHE without introducing noise artifacts, and structuring real-time probability outputs for intuitive clinician review.',
                    learned: 'Building medical computer vision systems requires bridging robust image preprocessing with responsive, unambiguous clinical user workflows.'
                },
                {
                    id: 'experience-infosys',
                    title: 'Infosys',
                    subtitle: 'Java Full Stack Developer Intern',
                    description: 'Hands-on training and development across enterprise Java, Spring Boot, REST microservices, cloud concepts, and agile workflows.',
                    longDescription: 'Completed comprehensive Java Full Stack training and development at Infosys Springboard. Engineered QuickServe (Localized Service Discovery & Booking Platform) using Spring Boot backend services, Hibernate/JPA, and modern web architecture.',
                    image: images.office,
                    year: '2025',
                    season: 'S01',
                    episode: 'E04',
                    duration: 'Certified',
                    rank: 4,
                    matchPercentage: 98,
                    maturityRating: 'ENTERPRISE',
                    specs: ['Spring Boot', 'Hibernate', 'Microservices'],
                    isOriginal: true,
                    runtime: 'Springboard Certified',
                    tags: ['Java', 'Spring Boot', 'SQL', 'Hibernate', 'REST APIs'],
                    tech: [
                        { name: 'Java' },
                        { name: 'Spring Boot' },
                        { name: 'Hibernate / JPA' },
                        { name: 'MySQL' },
                        { name: 'Agile / Git' }
                    ],
                    category: 'experience',
                    role: 'Java Full Stack Developer Intern',
                    githubUrl: experienceLinks.infosys.githubUrl,
                    certificateUrl: certificateLinks.infosys,
                    problem: 'Building robust, enterprise-ready microservices and service booking platform requiring high availability and clean layering.',
                    solution: 'Architected modular Spring Boot REST endpoints with proper exception handling, JPA repository data models, and automated build pipelines for QuickServe.',
                    built: [
                        'QuickServe backend RESTful service controllers in Spring Boot',
                        'Data persistence and ORM queries using JPA/Hibernate',
                        'Automated unit testing and API documentation contracts'
                    ],
                    challenge: 'Adhering to strict enterprise coding standards and optimizing relational query execution.',
                    learned: 'Writing resilient enterprise software requires disciplined domain modeling, clean code architecture, and thorough test coverage.'
                },
                {
                    id: 'experience-gfg',
                    title: 'GeeksforGeeks Student Chapter',
                    subtitle: 'Content Writer & Core Team Member',
                    description: 'Authored technical articles, coordinated educational coding workshops, and partnered with design teams for student outreach.',
                    longDescription: 'Served as Technical Content Writer for the GeeksforGeeks Student Chapter, authoring curated coding tutorials, algorithm explanations, and promoting campus technical events.',
                    image: images.team,
                    year: '2024 - 2025',
                    season: 'S01',
                    episode: 'E05',
                    rank: 5,
                    matchPercentage: 95,
                    maturityRating: 'LEADERSHIP',
                    specs: ['Technical Writing', 'Data Structures', 'Chapter Lead'],
                    runtime: 'Chapter Credential',
                    tags: ['Technical Writing', 'Data Structures', 'Community', 'Design'],
                    tech: [
                        { name: 'Technical Writing' },
                        { name: 'Data Structures' },
                        { name: 'Community Leadership' }
                    ],
                    category: 'certification',
                    role: 'Content Writer & Core Member',
                    certificateUrl: certificateLinks.geeksForGeeks,
                    problem: 'Making complex algorithms and development practices easy to understand for beginner and intermediate engineering students.',
                    solution: 'Structured and published approachable learning materials, problem breakdowns, and event coverage.',
                    built: [
                        'Curated algorithmic problem solving breakdowns',
                        'Technical guides and workshop presentation materials',
                        'Community outreach documentation and event copywriting'
                    ],
                    challenge: 'Communicating intricate computer science topics concisely and engagingly.',
                    learned: 'Explaining a concept clearly is the ultimate test of understanding it; communication is foundational to engineering impact.'
                },
                {
                    id: 'education',
                    title: 'B.Tech in Computer Science',
                    subtitle: 'Kalasalingam Academy of Research and Education',
                    description: 'Bachelor of Technology in Computer Science & Engineering (Graduated 2025). Rigorous foundations in algorithms, systems, and AI.',
                    longDescription: 'Graduated in Computer Science and Engineering with an emphasis on algorithms, object-oriented design, distributed databases, web engineering, and machine learning.',
                    image: images.campus,
                    year: '2021 - 2025',
                    season: 'S01',
                    episode: 'E06',
                    rank: 6,
                    matchPercentage: 96,
                    maturityRating: 'GRADUATE',
                    specs: ['Computer Science', 'Algorithms', 'KARE 2025'],
                    runtime: '4-Year Degree',
                    tags: ['Computer Science', 'Algorithms', 'Java', 'Web Dev', 'AI'],
                    tech: [
                        { name: 'Algorithms & Data Structures' },
                        { name: 'Java & OOP' },
                        { name: 'Database Systems' },
                        { name: 'Software Engineering' }
                    ],
                    category: 'education',
                    role: 'Computer Science Graduate',
                    problem: 'Acquiring deep theoretical and applied foundations across computer science disciplines.',
                    solution: 'Completed coursework, hands-on lab projects, competitive coding challenges, and capstone applied machine learning research.',
                    built: [
                        'Core algorithmic data structures implementations in Java',
                        'Relational database design and query optimization models',
                        'Healthcare machine learning capstone project'
                    ],
                    challenge: 'Balancing rigorous academics with independent product development and internship experience.',
                    learned: 'Strong fundamentals empower quick mastery of any emerging language, framework, or technology stack.'
                },
            ],
        },
        {
            title: 'Trending in AI & Computer Vision',
            eyebrow: 'INTELLIGENT SYSTEMS',
            variant: 'poster',
            items: [
                {
                    id: 'project-disease',
                    title: 'Alzheimer & Parkinson Prediction',
                    subtitle: 'Published IEEE Research & Deep Learning App',
                    description: 'An AI-powered web platform for early disease detection and risk classification using EfficientNetB0 transfer learning (Published in IEEE Xplore).',
                    longDescription: 'Published IEEE research and clinical web application presenting a robust deep learning model utilizing EfficientNetB0 transfer learning from ImageNet for early detection and differentiation of Alzheimer and Parkinson diseases, achieving 98% accuracy on 7,839 clinical images.',
                    image: images.research,
                    year: '2025',
                    season: 'S01',
                    episode: 'E01',
                    rank: 1,
                    matchPercentage: 99,
                    maturityRating: 'IEEE 2025',
                    specs: ['4K Ultra HD', 'EfficientNetB0', '98% Acc'],
                    isOriginal: true,
                    runtime: 'Published Paper',
                    tags: ['IEEE Published', 'EfficientNetB0', 'Transfer Learning', 'TensorFlow', 'Python', 'React', '98% Accuracy'],
                    tech: [
                        { name: 'EfficientNetB0' },
                        { name: 'Transfer Learning' },
                        { name: 'TensorFlow & Keras' },
                        { name: 'Python' },
                        { name: 'Flask / FastAPI' },
                        { name: 'React & Tailwind' }
                    ],
                    category: 'project',
                    role: 'Lead ML Researcher & Full-Stack Developer',
                    liveUrl: projectLinks.alzheimerParkinson.liveUrl,
                    githubUrl: projectLinks.alzheimerParkinson.githubUrl,
                    paperUrl: projectLinks.alzheimerParkinson.paperUrl,
                    abstract: "This work presents a strong deep learning model that uses transfer learning from ImageNet, based on the EfficientNetB0 architecture. To ensure stability and convergence, we trained it with the Adam optimizer, data augmentation, class weighting, and effective callbacks such as Model Checkpoint, Early Stopping, and ReduceLROnPlateau over 20 epochs. The model trained on a database of 7,839 images, which included Normal (Control) and Abnormal (Parkinson's & Alzheimer's Diseases) samples from the Kaggle dataset. It achieved 98% accuracy on the validation set, showing excellent performance. We tested it using AUC and K-fold cross-validation methods, which demonstrated strong classification abilities with a weighted average Precision, Recall, and F1 score of 98%. The model, using the Adam optimizer, aimed to reduce categorical cross-entropy loss and track accuracy during training. A Flask-based online interface was developed to allow easy image uploads and offer instant diagnostic predictions for real-time use and practical application. This effective model shows great promise as a tool for early detection and differentiation of complex neurological diseases, making it useful for clinical diagnostics.",
                    problem: 'Early neurodegenerative diagnosis pipelines often suffer from lack of transfer-learning integration, high false-positive rates, and inaccessible clinical visualization interfaces.',
                    solution: 'Engineered an EfficientNetB0 deep learning architecture with transfer learning from ImageNet, validated across 7,839 medical images with K-fold cross-validation and AUC, integrated into a real-time web diagnostic system.',
                    built: [
                        'EfficientNetB0 transfer learning architecture trained on 7,839 clinical images',
                        'Achieved 98% validation accuracy, 98% weighted Precision, Recall, and F1-score',
                        'Adam optimization with ReduceLROnPlateau, Early Stopping, and class weighting callbacks',
                        'Interactive React & Flask online interface for real-time scan uploads and instant diagnostic inference',
                        'Peer-reviewed and published in IEEE Xplore (Document ID: 11336514)'
                    ],
                    challenge: 'Ensuring training stability, addressing class imbalance across Parkinson and Alzheimer samples, and achieving real-time inference latency.',
                    learned: 'Combining state-of-the-art transfer learning with rigorous K-fold validation and intuitive web interfaces delivers clinically actionable AI systems.',
                },
                {
                    id: 'project-retinopathy',
                    title: 'Diabetic Retinopathy Detection System',
                    subtitle: 'The Retinal Screen / AI Computer Vision',
                    description: 'A full-stack AI system that analyzes retinal fundus images and classifies diabetic retinopathy severity across five clinical stages.',
                    longDescription: 'A full-stack computer vision application for automated diabetic retinopathy screening from retinal fundus images. The system combines a React-based clinical interface with a Python deep-learning backend to process retinal images and classify disease severity across five stages: No DR, Mild, Moderate, Severe, and Proliferative DR. The frontend handles image upload and visualization of prediction results, while the backend performs image preprocessing and CNN-based inference through a REST API. The preprocessing pipeline includes image resizing, normalization, and Contrast Limited Adaptive Histogram Equalization (CLAHE) to improve image quality before inference.',
                    image: images.retina,
                    year: '2024 - 2025',
                    season: 'S01',
                    episode: 'E03',
                    rank: 3,
                    matchPercentage: 97,
                    maturityRating: 'AI VISION',
                    specs: ['CLAHE CNN', 'Docker', '5-Stage'],
                    isOriginal: true,
                    runtime: 'Screening Demo',
                    tags: ['React', 'Python', 'TensorFlow', 'OpenCV', 'CLAHE', 'CNN', 'Tailwind CSS'],
                    tech: [
                        { name: 'React' },
                        { name: 'Axios' },
                        { name: 'Python' },
                        { name: 'TensorFlow / Keras' },
                        { name: 'OpenCV' },
                        { name: 'CLAHE Pipeline' },
                        { name: 'Flask / FastAPI' },
                        { name: 'Tailwind CSS' },
                        { name: 'Docker' }
                    ],
                    category: 'project',
                    role: 'Frontend Engineering, API Integration & ML Pipeline',
                    liveUrl: projectLinks.retinopathy.liveUrl,
                    githubUrl: projectLinks.retinopathy.githubUrl,
                    problem: 'Diabetic retinopathy screening requires specialized retinal fundus image analysis, where manual evaluation can be slow, resource-constrained, and prone to diagnostic bottlenecking in high-volume clinics.',
                    solution: 'Built a full-stack screening pipeline connecting a responsive React clinical interface to a Python inference REST API with OpenCV CLAHE enhancement and CNN severity classification.',
                    built: [
                        'Frontend: Responsive React interface for retinal fundus image upload and 5-stage diagnostic severity visualization using Axios',
                        'Backend & REST API: Python REST API with a /predict endpoint returning structured severity classes, confidence scores, and status',
                        'Computer Vision Pipeline: Image preprocessing with resizing, normalization, and Contrast Limited Adaptive Histogram Equalization (CLAHE)',
                        '5-Stage Classification: Neural model mapping predictions to No DR (0), Mild (1), Moderate (2), Severe (3), and Proliferative DR (4)',
                        'Deployment Architecture: Docker containerization and Vercel cloud deployment for reliable web availability'
                    ],
                    challenge: 'Enhancing low-contrast fundus scans using CLAHE without introducing noise artifacts, and structuring real-time probability outputs for intuitive clinician review.',
                    learned: 'Building medical computer vision systems requires bridging robust image preprocessing with responsive, unambiguous clinical user workflows.'
                },
            ],
        },
        {
            title: 'Critically Acclaimed Full-Stack Platforms',
            eyebrow: 'WEB & CLOUD PLATFORMS',
            variant: 'poster',
            items: [
                {
                    id: 'project-chitrakar',
                    title: 'ChitraKara',
                    subtitle: 'Custom Art Marketplace & Platform',
                    description: 'A full-stack MERN platform connecting independent artists with buyers for custom art commissions and real-time collaboration.',
                    longDescription: 'A comprehensive creator economy platform facilitating custom artwork requests, artist discovery, automated OTP authentication, instant messaging, and secure media workflows.',
                    image: images.art,
                    year: '2024',
                    season: 'S01',
                    episode: 'E02',
                    rank: 2,
                    matchPercentage: 98,
                    maturityRating: 'LIVE APP',
                    specs: ['Full Stack', 'Cloudinary', 'Real-Time'],
                    isOriginal: true,
                    runtime: 'Live Platform',
                    tags: ['MongoDB', 'Express', 'React', 'Node.js', 'Cloudinary'],
                    tech: [
                        { name: 'MongoDB' },
                        { name: 'Express' },
                        { name: 'React' },
                        { name: 'Node.js' },
                        { name: 'Cloudinary' }
                    ],
                    category: 'project',
                    role: 'Full-Stack MERN Developer',
                    liveUrl: projectLinks.chitrakar.liveUrl,
                    githubUrl: projectLinks.chitrakar.githubUrl,
                    problem: 'Commissioning custom art is often chaotic when spread across fragmented email threads and direct messages without milestone tracking.',
                    solution: 'Built a dedicated two-sided marketplace featuring real-time client-artist chat, OTP verified security, and structured commission workflows.',
                    built: [
                        'Secure OTP authentication flow and profile management',
                        'Real-time messaging channels for artwork specs and negotiations',
                        'Cloudinary digital asset management and portfolio galleries'
                    ],
                    challenge: 'Managing bidirectional state and media uploads across multi-role artist and buyer dashboards.',
                    learned: 'Designing seamless user flows for bilateral platforms requires thorough role permissioning and responsive state architecture.',
                },
                {
                    id: 'experience-infosys',
                    title: 'QuickServe (Infosys Internship)',
                    subtitle: 'Localized Service Discovery & Booking Platform',
                    description: 'Enterprise Java & Spring Boot microservice architecture for geo-localized service bookings with JPA persistence.',
                    longDescription: 'Completed comprehensive Java Full Stack training and development at Infosys Springboard. Engineered QuickServe (Localized Service Discovery & Booking Platform) using Spring Boot backend services, Hibernate/JPA, and modern web architecture.',
                    image: images.office,
                    year: '2025',
                    season: 'S01',
                    episode: 'E04',
                    duration: 'Certified',
                    rank: 4,
                    matchPercentage: 98,
                    maturityRating: 'ENTERPRISE',
                    specs: ['Spring Boot', 'Hibernate', 'Microservices'],
                    isOriginal: true,
                    runtime: 'Springboard Certified',
                    tags: ['Java', 'Spring Boot', 'SQL', 'Hibernate', 'REST APIs'],
                    tech: [
                        { name: 'Java' },
                        { name: 'Spring Boot' },
                        { name: 'Hibernate / JPA' },
                        { name: 'MySQL' },
                        { name: 'Agile / Git' }
                    ],
                    category: 'experience',
                    role: 'Java Full Stack Developer Intern',
                    githubUrl: experienceLinks.infosys.githubUrl,
                    certificateUrl: certificateLinks.infosys,
                    problem: 'Building robust, enterprise-ready microservices and service booking platform requiring high availability and clean layering.',
                    solution: 'Architected modular Spring Boot REST endpoints with proper exception handling, JPA repository data models, and automated build pipelines for QuickServe.',
                    built: [
                        'QuickServe backend RESTful service controllers in Spring Boot',
                        'Data persistence and ORM queries using JPA/Hibernate',
                        'Automated unit testing and API documentation contracts'
                    ],
                    challenge: 'Adhering to strict enterprise coding standards and optimizing relational query execution.',
                    learned: 'Writing resilient enterprise software requires disciplined domain modeling, clean code architecture, and thorough test coverage.'
                },
            ],
        },
        {
            title: 'Documentary Episodes & Milestones',
            eyebrow: 'EXPERIENCE & CREDENTIALS',
            variant: 'landscape',
            items: [
                {
                    id: 'experience-infosys',
                    title: 'Infosys',
                    subtitle: 'Java Full Stack Developer Intern',
                    description: 'Hands-on training and development across enterprise Java, Spring Boot, REST microservices, cloud concepts, and agile workflows.',
                    longDescription: 'Completed comprehensive Java Full Stack training and development at Infosys Springboard. Engineered QuickServe (Localized Service Discovery & Booking Platform) using Spring Boot backend services, Hibernate/JPA, and modern web architecture.',
                    image: images.office,
                    year: '2025',
                    season: 'S01',
                    episode: 'E04',
                    duration: 'Certified',
                    rank: 4,
                    matchPercentage: 98,
                    maturityRating: 'ENTERPRISE',
                    specs: ['Spring Boot', 'Hibernate', 'Microservices'],
                    isOriginal: true,
                    runtime: 'Springboard Certified',
                    tags: ['Java', 'Spring Boot', 'SQL', 'Hibernate', 'REST APIs'],
                    tech: [
                        { name: 'Java' },
                        { name: 'Spring Boot' },
                        { name: 'Hibernate / JPA' },
                        { name: 'MySQL' },
                        { name: 'Agile / Git' }
                    ],
                    category: 'experience',
                    role: 'Java Full Stack Developer Intern',
                    githubUrl: experienceLinks.infosys.githubUrl,
                    certificateUrl: certificateLinks.infosys,
                    problem: 'Building robust, enterprise-ready microservices and service booking platform requiring high availability and clean layering.',
                    solution: 'Architected modular Spring Boot REST endpoints with proper exception handling, JPA repository data models, and automated build pipelines for QuickServe.',
                    built: [
                        'QuickServe backend RESTful service controllers in Spring Boot',
                        'Data persistence and ORM queries using JPA/Hibernate',
                        'Automated unit testing and API documentation contracts'
                    ],
                    challenge: 'Adhering to strict enterprise coding standards and optimizing relational query execution.',
                    learned: 'Writing resilient enterprise software requires disciplined domain modeling, clean code architecture, and thorough test coverage.'
                },
                {
                    id: 'experience-gfg',
                    title: 'GeeksforGeeks Student Chapter',
                    subtitle: 'Content Writer & Core Team Member',
                    description: 'Authored technical articles, coordinated educational coding workshops, and partnered with design teams for student outreach.',
                    longDescription: 'Served as Technical Content Writer for the GeeksforGeeks Student Chapter, authoring curated coding tutorials, algorithm explanations, and promoting campus technical events.',
                    image: images.team,
                    year: '2024 - 2025',
                    season: 'S01',
                    episode: 'E05',
                    rank: 5,
                    matchPercentage: 95,
                    maturityRating: 'LEADERSHIP',
                    specs: ['Technical Writing', 'Data Structures', 'Chapter Lead'],
                    runtime: 'Chapter Credential',
                    tags: ['Technical Writing', 'Data Structures', 'Community', 'Design'],
                    tech: [
                        { name: 'Technical Writing' },
                        { name: 'Data Structures' },
                        { name: 'Community Leadership' }
                    ],
                    category: 'certification',
                    role: 'Content Writer & Core Member',
                    certificateUrl: certificateLinks.geeksForGeeks,
                    problem: 'Making complex algorithms and development practices easy to understand for beginner and intermediate engineering students.',
                    solution: 'Structured and published approachable learning materials, problem breakdowns, and event coverage.',
                    built: [
                        'Curated algorithmic problem solving breakdowns',
                        'Technical guides and workshop presentation materials',
                        'Community outreach documentation and event copywriting'
                    ],
                    challenge: 'Communicating intricate computer science topics concisely and engagingly.',
                    learned: 'Explaining a concept clearly is the ultimate test of understanding it; communication is foundational to engineering impact.'
                },
                {
                    id: 'education',
                    title: 'B.Tech in Computer Science',
                    subtitle: 'Kalasalingam Academy of Research and Education',
                    description: 'Bachelor of Technology in Computer Science & Engineering (Graduated 2025). Rigorous foundations in algorithms, systems, and AI.',
                    longDescription: 'Graduated in Computer Science and Engineering with an emphasis on algorithms, object-oriented design, distributed databases, web engineering, and machine learning.',
                    image: images.campus,
                    year: '2021 - 2025',
                    season: 'S01',
                    episode: 'E06',
                    rank: 6,
                    matchPercentage: 96,
                    maturityRating: 'GRADUATE',
                    specs: ['Computer Science', 'Algorithms', 'KARE 2025'],
                    runtime: '4-Year Degree',
                    tags: ['Computer Science', 'Algorithms', 'Java', 'Web Dev', 'AI'],
                    tech: [
                        { name: 'Algorithms & Data Structures' },
                        { name: 'Java & OOP' },
                        { name: 'Database Systems' },
                        { name: 'Software Engineering' }
                    ],
                    category: 'education',
                    role: 'Computer Science Graduate',
                    problem: 'Acquiring deep theoretical and applied foundations across computer science disciplines.',
                    solution: 'Completed coursework, hands-on lab projects, competitive coding challenges, and capstone applied machine learning research.',
                    built: [
                        'Core algorithmic data structures implementations in Java',
                        'Relational database design and query optimization models',
                        'Healthcare machine learning capstone project'
                    ],
                    challenge: 'Balancing rigorous academics with independent product development and internship experience.',
                    learned: 'Strong fundamentals empower quick mastery of any emerging language, framework, or technology stack.'
                },
            ],
        },
    ],
    journey: [
        { code: 'S01 E01', title: 'The Spark', description: 'Began writing code, learning programming foundations, and developing algorithmic thinking.' },
        { code: 'S01 E02', title: 'The Builder', description: 'Ventured into full-stack web development with React, Node.js, and building real-world dynamic web applications like ChitraKara.' },
        { code: 'S01 E03', title: 'The Visionary & Researcher', description: 'Explored deep learning, medical imaging AI, and computer vision systems (Alzheimer/Parkinson IEEE paper & Retinopathy screening).' },
        { code: 'S01 E04', title: 'The Enterprise Engineer', description: 'Deepened enterprise software skills with Java, Spring Boot, microservices architecture, and completed the Infosys internship with QuickServe.' },
        { code: 'S01 E05', title: "What's Next", description: 'Building high-performance software systems, expanding AI-driven applications, and documenting the next chapter.' },
    ],
    toolkit: [
        { label: 'Backend', items: ['Java', 'Spring Boot', 'Node.js', 'Express.js', 'REST APIs', 'Hibernate/JPA'] },
        { label: 'Frontend', items: ['React', 'TypeScript', 'JavaScript (ES6+)', 'Tailwind CSS', 'HTML5 & CSS3'] },
        { label: 'Database', items: ['MySQL', 'PostgreSQL', 'MongoDB', 'Database Modeling'] },
        { label: 'AI & Vision', items: ['Python', 'TensorFlow', 'OpenCV', 'CLAHE', 'Machine Learning', 'CNNs'] },
        { label: 'Tools & DevOps', items: ['Git & GitHub', 'Docker', 'Vite', 'Postman', 'Cloudinary', 'Figma'] },
    ],
    currentlyBuilding: {
        title: 'Documentary Portfolio & AI Systems',
        status: 'In Active Development',
        description: 'Refining full-stack production architectures, building intelligent applications, and documenting software journeys as living archives.'
    },
    beyondCode: ['Cinema & Documentaries', 'Anime & Storytelling', 'Technical Writing', 'UI/UX Design', 'Continuous Learning', 'Open Source'],
    about: {
        name: 'Bala Rajesh',
        role: 'Software Engineer / Full-Stack Developer',
        description: 'A passionate developer exploring Java, Spring Boot, React, and artificial intelligence. Dedicated to building performant, reliable, and user-centric digital products that solve genuine real-world challenges.',
        image: profileImg,
    },
};
